version: '1.0'
services:
  backend:
    build: backend
    container_name: backend
    ports:
      - 8080:8080
  frontend:
    build: frontend
    container_name: frontend
    ports:
      - 80:3000
    depends_on:
      - backend